# -*- coding: utf-8 -*-
"""Copy of CIS156_PS5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_g5xkKhZPizD-Ifvkl7Ty2kkhex-Mnkz

please download the [words.txt](https://drive.google.com/file/d/1CTaQ5fhHiakivdaosFuyyVvRhvKW7_m_/view?usp=sharing) and [story.txt](https://drive.google.com/file/d/1Bxnss7vPayxGDHsEjOWAoN3kk3hbke8e/view?usp=sharing) and upload to your /content/words.txt and /content/story.txt to test these code!

Note: all attached files are supposed to be uploaded to /content dir
like /content/story.txt y /content/words.txt

PS1 Prompt:

Encryption is the process of obscuring information to make it unreadable without special knowledge. For centuries, people have devised schemes to encrypt messages - some better than others - but the advent of the computer and the Internet revolutionized the field. These days, it's hard not to encounter some sort of encryption, whether you are buying something online or logging into a shared computer system. Encryption lets you share information with other trusted people, without fear of disclosure.
A cipher is an algorithm for performing encryption (and the reverse, decryption). The original information is called plaintext. After it is encrypted, it is called ciphertext. The ciphertext message contains all the information of the plaintext message, but it is not in a format readable by a human or computer without the proper mechanism to decrypt it; it should resemble random gibberish to those for whom it is not intended.
A cipher usually depends on a piece of auxiliary information, called a key. The key is incorporated into the encryption process; the same plaintext encrypted with two different keys should have two different ciphertexts. Without the key, it should be difficult to decrypt the resulting ciphertext into readable plaintext.
This assignment will deal with a well-known (though not very secure) encryption method called the Caesar cipher. Some vocabulary to get you started on this problem:
Encryption - the process of obscuring or encoding messages to make them unreadable until they are decrypted
Decryption - making encrypted messages readable again by decoding them
Cipher - algorithm for performing encryption and decryption
Plaintext - the original message
Ciphertext - the encrypted message. Note: a ciphertext still contains all of the original message information, even if it looks like gibberish.
The Caesar Cipher
The idea of the Caesar Cipher is to pick an integer and shift every letter of your message by that integer. In other words, suppose the shift is k . Then, all instances of the i-th letter of the alphabet that appear in the plaintext should become the (i+k)-th letter of the alphabet in the ciphertext. You will need to be careful with the case in which i + k > 26 (the length of the alphabet). Here is what the whole alphabet looks like shifted three spots to the right:
Original:  a b c d e f g h i j k l m n o p q r s t u v w x y z
 3-shift:  d e f g h i j k l m n o p q r s t u v w x y z a b c
Using the above key, we can quickly translate the message "happy" to "kdssb" (note how the 3-shifted alphabet wraps around at the end, so x -> a, y -> b, and z -> c).
Note!! We are using the English alphabet for this problem - that is, the following letters in the following order:
>>> import string
>>> print string.ascii_lowercase
abcdefghijklmnopqrstuvwxyz
We will treat uppercase and lowercase letters individually, so that uppercase letters are always mapped to an uppercase letter, and lowercase letters are always mapped to a lowercase letter. If an uppercase letter maps to "A", then the same lowercase letter should map to "a". Punctuation and spaces should be retained and not changed. For example, a plaintext message with a comma should have a corresponding ciphertext with a comma in the same position.
|    plaintext    |  shift    |  ciphertext      |
| ----------------|-----------|------------------|
| 'abcdef'        |    2      |  'cdefgh'        |
| 'Hello, World!' |    5      |  'Mjqqt, Btwqi!' |
| ''              | any value |  ''              |

We implemented for you two helper functions: load_words and is_word. You may use these in your solution and you do not need to understand them completely, but should read the associated comments. You should read and understand the helper code in the rest of the file and use it to guide your solutions.
Getting Started
To get started, download the ps6.zip file. Extract it to your working directory. The files inside are:
ps6.py - a file containing three classes that you will have to implement.
words.txt - a file containing valid English words (should be in the same folder as your ps6..py file).
story.txt - a file containing an encrypted message that you will have to decode (should be in the same folder as your ps6..py file).
This will be your first experience coding with classes! We will have a Message class with two subclasses PlaintextMessage and CiphertextMessage .























Problem 1 - Build the Shift Dictionary and Apply Shift
0.0/20.0 points (graded)
The Message class contains methods that could be used to apply a cipher to a string, either to encrypt or to decrypt a message (since for Caesar codes this is the same action).
In the next two questions, you will fill in the methods of the Message class found in ps6.py according to the specifications in the docstrings. The methods in the Message class already filled in are:
__init__(self, text)
The getter method get_message_text(self)
The getter method get_valid_words(self), notice that this one returns a copy of self.valid_words to prevent someone from mutating the original list.
In this problem, you will fill in two methods:
Fill in the build_shift_dict(self, shift) method of the Message class. Be sure that your dictionary includes both lower and upper case letters, but that the shifted character for a lower case letter and its uppercase version are lower and upper case instances of the same letter. What this means is that if the original letter is "a" and its shifted value is "c", the letter "A" should shift to the letter "C".
If you are unfamiliar with the ordering or characters of the English alphabet, we will be following the letter ordering displayed by string.ascii_lowercase and string.ascii_uppercase:
>>> import string
>>> print(string.ascii_lowercase)
abcdefghijklmnopqrstuvwxyz
>>> print(string.ascii_uppercase)
ABCDEFGHIJKLMNOPQRSTUVWXYZ
A reminder from the introduction page - characters such as the space character, commas, periods, exclamation points, etc will not be encrypted by this cipher - basically, all the characters within string.punctuation, plus the space (' ') and all numerical characters (0 - 9) found in string.digits.
Fill in the apply_shift(self, shift) method of the Message class. You may find it easier to use build_shift_dict(self, shift). Remember that spaces and punctuation should not be changed by the cipher.





























Problem 2 - PlaintextMessage
0.0/15.0 points (graded)
PlaintextMessage is a subclass of Message and has methods to encode a string using a specified shift value. Our class will always create an encoded version of the message, and will have methods for changing the encoding.
Implement the methods in the class PlaintextMessage according to the specifications in ps6.py. The methods you should fill in are:
__init__(self, text, shift): Use the parent class constructor to make your code more concise.
The getter method get_shift(self)
The getter method get_encrypting_dict(self): This should return a COPY of self.encrypting_dict to prevent someone from mutating the original dictionary.
The getter method get_message_text_encrypted(self)
change_shift(self, shift): Think about what other methods you can use to make this easier. It shouldn’t take more than a couple lines of code.
















Problem 3 - CiphertextMessage
0.0/15.0 points (graded)
Given an encrypted message, if you know the shift used to encode the message, decoding it is trivial. If message is the encrypted message, and s is the shift used to encrypt the message, then apply_shift(message, 26-s) gives you the original plaintext message. Do you see why?
The problem, of course, is that you don’t know the shift. But our encryption method only has 26 distinct possible values for the shift! We know English is the main language of these emails, so if we can write a program that tries each shift and maximizes the number of English words in the decoded message, we can decrypt their cipher! A simple indication of whether or not the correct shift has been found is if most of the words obtained after a shift are valid words. Note that this only means that most of the words obtained are actual words. It is possible to have a message that can be decoded by two separate shifts into different sets of words. While there are various strategies for deciding between ambiguous decryptions, for this problem we are only looking for a simple solution.
Fill in the methods in the class CiphertextMessage according to the specifications in ps6.py. The methods you should fill in are:
__init__(self, text): Use the parent class constructor to make your code more concise.
decrypt_message(self): You may find the helper function is_word(wordlist, word) and the string method split() useful. Note that is_word will ignore punctuation and other special characters when considering whether a word is valid.
You may find the function string.split useful for dividing the text up into words.>>> 'Hello world!'.split('o')['Hell', ' w', 'rld!']


Problem 4 - Decrypt a Story
0.0/5.0 points (graded)
Now that you have all the pieces to the puzzle, please use them to decode the file story.txt. The file ps6.py contains a helper function get_story_string() that returns the encrypted version of the story as a string. Create a CiphertextMessage object using the story string and use decrypt_message to return the appropriate shift value and unencrypted story string.
"""

#Import Section
import string
import os



# Define load_words function
WORDLIST_FILENAME = 'words.txt'
STORY_FILENAME = 'story.txt'

def load_words(file_name="words.txt"):
    # Open 'words.txt', read words from the file, and return
    print('Loading word list from file...')
    line = open(file_name, 'r').readline()
    word_list = line.split()
    print('  ', len(word_list), 'words loaded.')
    open(file_name, 'r').close()
    return word_list

# Define is_word function
def is_word(word_list, word):
   # Check if a cleaned version of a word is in the list
    word = word.lower()
    word = word.strip(" !@#$%^&*()-_+={}[]|\:;'<>?,./\"")
    return word in word_list

# Define get_story_string function
def get_story_string():
    # Open 'story.txt', read its content, and return
    f = open("story.txt", "r")
    story = str(f.read())
    f.close()
    return story

WORDLIST_FILENAME = 'words.txt'

# Define Message class
class Message(object):
  # Initialize with text and load valid words
    def __init__(self, text):
        self.message_text = text
        self.valid_words = load_words(WORDLIST_FILENAME)

  #Return original message
    def get_message_text(self):
        return self.message_text

  #Return a copy of the valid words
    def get_valid_words(self):
        return self.valid_words[:]

  #Build a dictionary to map letters to their shift value
    def build_shift_dict(self, shift):
        shift_dict = {}
        lower = string.ascii_lowercase
        upper = string.ascii_uppercase

        for i in range(26):
            shift_dict[lower[i]] = lower[(i + shift) % 26]
            shift_dict[upper[i]] = upper[(i + shift) % 26]

        return shift_dict

  #Encrypt or decrypt the text using the shift dictionary
    def apply_shift(self, shift):
        shift_dict = self.build_shift_dict(shift)
        encrypted_text = ""

        for char in self.message_text:
            if char in shift_dict:
                encrypted_text += shift_dict[char]
            else:
                encrypted_text += char

        return encrypted_text

# Define PlaintextMessage class
class PlaintextMessage(Message):
   # Initialize with text and shift to generate encrypted text
    def __init__(self, text, shift):
        super().__init__(text)
        self.shift = shift
        self.encrypting_dict = self.build_shift_dict(shift)
        self.message_text_encrypted = self.apply_shift(shift)

  # Return the shift value
    def get_shift(self):
        return self.shift

  # Return the shift dictionary
    def get_encrypting_dict(self):
        return self.encrypting_dict.copy()

  # Return the encrypted message text
    def get_message_text_encrypted(self):
        return self.message_text_encrypted

  # Update the shift value and re-encrypt the text
    def change_shift(self, shift):
        self.shift = shift
        self.encrypting_dict = self.build_shift_dict(shift)
        self.message_text_encrypted = self.apply_shift(shift)

# Define CiphertextMessage class
class CiphertextMessage(Message):
    # Initialize with text for decryption
    def __init__(self, text):
        super().__init__(text)

  # Attempt all shifts, returning the plaintext
    def decrypt_message(self):
        best_shift = 0
        max_valid_words = 0
        decrypted_message = ""

        for shift in range(26):
            decoded_text = self.apply_shift(26 - shift)
            word_count = sum(is_word(self.valid_words, word) for word in decoded_text.split())

            if word_count > max_valid_words:
                best_shift = 26 - shift
                max_valid_words = word_count
                decrypted_message = decoded_text

        return best_shift, decrypted_message

# Execution
if __name__ == "__main__":
    # Test encryption
    plaintext = PlaintextMessage('hello', 2)
    print('Expected Output: jgnnq')
    print('Actual Output:', plaintext.get_message_text_encrypted())
    # Test decryption
    ciphertext = CiphertextMessage('jgnnq')
    print('Expected Output:', (24, 'hello'))
    print('Actual Output:', ciphertext.decrypt_message())
    # Decrypt story text
    ciphertext = CiphertextMessage(get_story_string())
    print('Decrypted Story:', ciphertext.decrypt_message())